import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import MainLayout from "@/layout/MainLayout";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`  ${PoppinsFont.variable}   `} suppressHydrationWarning>
        <MainLayout>
          {children}
        </MainLayout>
             {/* ✅ Botpress scripts */}
        <Script src="https://cdn.botpress.cloud/webchat/v3.2/inject.js" />
        <Script
          src="https://files.bpcontent.cloud/2025/08/28/06/20250828062448-9KMG6PYU.js"
          strategy="lazyOnload"/>
      </body>
    </html>
  );
}
